#!bash 
sudo su
yum install python3.7
yum install python-pip
pip install pipenv
pipenv --three
pipenv install django
yum install git
git clone https://github.com/DanielRGrant/Retrobase.git
cd Retrobase


#get latest sqlite
yum groupinstall "Development Tools"
yum install tcl
curl -O https://www.sqlite.org/src/tarball/sqlite.tar.gz
tar -xvf sqlite.tar.gz
cd sqlite/
./configure
make
cp -v .libs/libsqlite3.so.0.8.6 /usr/local/lib64/
    # Dont miss the dot in .libs above
echo "/usr/local/lib64" > /etc/ld.so.conf.d/sqlite-x68_64.conf
ldconfig